[project]
name = "grpo_example"
version = "0.1.0"
description = "GRPO training example"
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []