REFERENCE_MODEL_NAME = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

TRAIN_DEVICES = [0, 1, 2, 3]

GPU = f"H100:{str(1 + len(TRAIN_DEVICES))}"
TRAIN_CUDA_VISIBLE_DEVICES = ",".join(map(str, TRAIN_DEVICES))
TRAIN_NUM_PROCESSES = str(len(TRAIN_DEVICES))
VLLM_CUDA_VISIBLE_DEVICES = str(len(TRAIN_DEVICES))
MAX_PROMPT_LENGTH = 3072
MAX_COMPLETION_LENGTH = 2048

TRAIN_NUM_GPUS = TRAIN_CUDA_VISIBLE_DEVICES.count(",") + 1
NUM_GENERATIONS = 4
