REFERENCE_MODEL_NAME = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

GPU = "H100:5"
TRAIN_CUDA_VISIBLE_DEVICES = "0,1,2,3"
TRAIN_NUM_PROCESSES = "4"
VLLM_CUDA_VISIBLE_DEVICES = "4"

TRAIN_NUM_GPUS = TRAIN_CUDA_VISIBLE_DEVICES.count(",") + 1
NUM_GENERATIONS = 8
