REFERENCE_MODEL_NAME = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

GPU = "H100:5"
TRAIN_CUDA_VISIBLE_DEVICES = "0,1,2,3"
TRAIN_NUM_PROCESSES = "4"
VLLM_CUDA_VISIBLE_DEVICES = "4"
MAX_PROMPT_LENGTH = 3072
MAX_COMPLETION_LENGTH = 1024

TRAIN_NUM_GPUS = TRAIN_CUDA_VISIBLE_DEVICES.count(",") + 1
NUM_GENERATIONS = 16
